function out1 = CalculateJ_linear(v,r,d_phi,e,a_wheel_angle)
%CALCULATEJ_LINEAR
%    OUT1 = CALCULATEJ_LINEAR(V,R,D_PHI,E,A_WHEEL_ANGLE)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    14-Apr-2020 15:27:15

t3 = v.*(1.0./3.3e1);
t5 = r.*4.648484848484848e-2;
t2 = -t3+t5;
t10 = r.*3.048484848484848e-2;
t4 = t3+t10;
t6 = t2.^2;
t7 = t6+1.0;
t8 = 1.0./t7;
t9 = cos(a_wheel_angle);
t11 = t4.^2;
t12 = t11+1.0;
t13 = 1.0./t12;
t14 = sin(a_wheel_angle);
t15 = atan(t4);
out1 = reshape([t8.*(-2.689798464446352)-t9.*t13.*2.051000642549938,t8.*2.239598488348856-t9.*t13.*1.119924748386965,0.0,1.0,0.0,t8.*4.126150844460704-t9.*t13.*2.063306646405238-3.3e1,t8.*(-3.435544081127145)-t9.*t13.*1.126644296877287,1.0,0.0,0.0,0.0,0.0,0.0,3.3e1,0.0,0.0,0.0,0.0,0.0,0.0,t9.*6.768302120414796e1-t14.*(a_wheel_angle.*8.746e4-t15.*8.746e4).*7.73874013310633e-4,t9.*3.695751669676986e1-t14.*(a_wheel_angle.*8.798476e4-t15.*8.798476e4).*4.200445247196203e-4,0.0,0.0,0.0],[5,5]);
